### ISSUE TITLE
Error Command nenuphar gen

### ISSUE THREAD

**Issue by yusriltakeuchi** [PiotrFLEURY/nenuphar_cli#21]
I found error when using nenuphar gen command, it's someting not found allowed method.
 evaluating path: \api\auth\login
No allowed methods found for \api\auth\login
Using default allowed methods: [options, get, head, post, put, patch, delete]
 evaluating path: \api\auth\register
No allowed methods found for \api\auth\register
Using default allowed methods: [options, get, head, post, put, patch, delete]

This is my route login
```dart
import 'dart:io';
import 'package:dart_frog/dart_frog.dart';
import 'package:travel_plan/controller/auth/auth_controller.dart';

Future<Response> onRequest(RequestContext context) async {
  return switch(context.request.method) {
    HttpMethod.post => AuthController.instance.login(context),
    _ => Future.value(Response(statusCode: HttpStatus.methodNotAllowed))
  };
}
```

This is my route register
```dart
import 'dart:io';
import 'package:dart_frog/dart_frog.dart';
import 'package:travel_plan/controller/auth/auth_controller.dart';

Future<Response> onRequest(RequestContext context) async {
  return switch(context.request.method) {
    HttpMethod.post => AuthController.instance.register(context),
    _ => Future.value(Response(statusCode: HttpStatus.methodNotAllowed))
  };
}
```

**Comment by yusriltakeuchi** [comment]
Update:
I add comment section for Allow Method like this:
```dart
///
/// The /api/auth/login routes
///
/// @Allow(POST) - Allow only POST methods
///
/// @Header(User-Name) - The user name header
///
///
Future<Response> onRequest(RequestContext context) async {
  return switch(context.request.method) {
    HttpMethod.post => AuthController.instance.login(context),
    _ => Future.value(Response(statusCode: HttpStatus.methodNotAllowed))
  };
}
```

But still error:
- nenuphar gen
Will generate OpenAPI file
input is: C:\Users\User\Documents\Project\flutter\other\travel_plan
Found C:\Users\User\Documents\Project\flutter\other\travel_plan/routes\index.dart
C:\Users\User\Documents\Project\flutter\other\travel_plan/routes\api\auth\login.dart
C:\Users\User\Documents\Project\flutter\other\travel_plan/routes\api\auth\register.dart
C:\Users\User\Documents\Project\flutter\other\travel_plan/routes\api\profile\index.dart
C:\Users\User\Documents\Project\flutter\other\travel_plan/routes\api\travel\index.dart
C:\Users\User\Documents\Project\flutter\other\travel_plan/routes\api\travel\[id].dart routes
 evaluating path: \index
 evaluating path: \api\auth\login
 evaluating path: \api\auth\register
 evaluating path: \api\profile\index
 evaluating path: \api\travel\index
 evaluating path: \api\travel\{id}
Failed to generate OpenAPI file: Bad state: No element

**Comment by PiotrFLEURY** [comment]
Thanks for your feeback @yusriltakeuchi 

I successfully reproduced your issue and fixed it.

You use case has also been added to the automated tests.

The fix has been tested on Windows 10 and validated.

You can update to `0.0.10` version to get the fix.

Feel free to let me know if you face any other issue.

Thank you for using Nenuphar 🚀

**Comment by yusriltakeuchi** [comment]
> Thanks for your feeback @yusriltakeuchi
> 
> I successfully reproduced your issue and fixed it.
> 
> You use case has also been added to the automated tests.
> 
> The fix has been tested on Windows 10 and validated.
> 
> You can update to `0.0.10` version to get the fix.
> 
> Feel free to let me know if you face any other issue.
> 
> Thank you for using Nenuphar 🚀

Do you have an example for commenting in route to generate field in swagger? 
Like how to give an example request body, available authorization, and many more?

**Comment by yusriltakeuchi** [comment]
> Thanks for your feeback @yusriltakeuchi
> 
> I successfully reproduced your issue and fixed it.
> 
> You use case has also been added to the automated tests.
> 
> The fix has been tested on Windows 10 and validated.
> 
> You can update to `0.0.10` version to get the fix.
> 
> Feel free to let me know if you face any other issue.
> 
> Thank you for using Nenuphar 🚀

Hi, how we can input basic information about the swagger documentations like this?
```json
{
  "title": "Sample Pet Store App",
  "summary": "A pet store manager.",
  "description": "This is a sample server for a pet store.",
  "termsOfService": "https://example.com/terms/",
  "contact": {
    "name": "API Support",
    "url": "https://www.example.com/support",
    "email": "support@example.com"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "version": "1.0.1"
}
```

Is that have any setting to generate this?

**Comment by PiotrFLEURY** [comment]
Hi @yusriltakeuchi 

Thanks for your e-mail question about basic openapi informations.

You can specify them by editing the nenuphar.json file à the root level of your project.
This file should have been generated by the nenuphar init command.

For more informations please follow the link bellow.

https://piotrfleury.github.io/nenuphar_cli/#nenupharjson-file
