### ISSUE TITLE
`nenuphar gen` results in openapi.json including '\\' (instead of '/' which is intended) in windows

### ISSUE THREAD

**Issue by chan150** [PiotrFLEURY/nenuphar_cli#22]
**Description**
`nenuphar gen` results in openapi.json including '\\' (instead of '/' which is intended) in windows

**Steps To Reproduce**

1. run `nenuphar gen`
2. cd public
3. run `jq . openapi.json` to make json pretty
4. run `cat openapi.json | grep '\\' | wc -l` to count '\\' letters
240

**Expected Behavior**

It should not contain '\\' which have to be replaced with '/'.

4. run `cat openapi.json | grep '\\' | wc -l` to count '\\' letters
0

**Comment by PiotrFLEURY** [comment]
Thanks for your feeback @chan150 

Windiws `\\` filesystem path separators are now replaced by `/` API path separators.

I also updated the automated tests to secure this modification.

You can update to `0.0.10` version to get the fix.

Feel free to let me know if you face any other issue.

Thank you for using Nenuphar 🚀
