### ISSUE TITLE
API including [message].dart will make an error with "Failed to generate OpenAPI file: Bad state: No element" in Windows

### ISSUE THREAD

**Issue by chan150** [PiotrFLEURY/nenuphar_cli#23]
**Description**

API including [message].dart will make an error with "Failed to generate OpenAPI file: Bad state: No element" in Windows

**Steps To Reproduce**

1. Creating a dynamic route `touch routes/[message].dart`
2. vim routes/[message].dart
```dart
import 'package:dart_frog/dart_frog.dart';

Response onRequest(RequestContext context, String message) {
  return Response(body: message);
}
```
3. Run `nenuphar gen`
```shell
nenuphar gen                       
Will generate OpenAPI file
input is: D:\workspace\test
Found D:\workspace\test/routes\index.dart
D:\test/routes\[message].dart routes
 evaluating path: \index
No allowed methods found for \index
Using default allowed methods: [options, get, head, post, put, patch, delete]
 evaluating path: \{message}
Failed to generate OpenAPI file: Bad state: No element
```

**Expected Behavior**

Linux will produce document well, but Windows fail.

**Comment by PiotrFLEURY** [comment]
Thanks for your feeback @chan150 

I successfully reproduced your issue and fixed it.

You use case has also been added to the automated tests.

The fix has been tested on Windows 10 and validated.

You can update to `0.0.10` version to get the fix.

Feel free to let me know if you face any other issue.

Thank you for using Nenuphar 🚀
